- name: Install git
  package:
      name: git
      state: latest
  become: yes
  become_user: root
  become_method: sudo

- name: Install git-delta
  package:
      name: git-delta
      state: latest
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- block:
    - name: Get latest version
      uri:
          url: https://api.github.com/repos/dandavison/delta/releases/latest
          return_content: true
      register: json_response

    - name: Install delta
      apt:
          deb: https://github.com/dandavison/delta/releases/download/{{ json_response.json.name }}/git-delta_{{ json_response.json.name }}_{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}.deb
      become: yes
      become_user: root
      become_method: sudo
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Link global gitignore file
  file:
      src: ".local/ansible/roles/git/files/gitignore_global.link"
      dest: "~/.gitignore_global"
      state: link
      force: yes

- name: Check if gitconfig exists
  stat: path="~/.gitconfig"
  register: gitconfig_stat

- name: Backup gitconfig
  command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
      creates: "~/gitconfig.bak"
  when: gitconfig_stat.stat.exists

- name: Set git config
  template:
      src: "gitconfig.j2"
      dest: "~/.gitconfig"
